language: php

php:
  - 7.4

cache:
  directories:
    - $HOME/.cache/composer
    - $HOME/.php-cs-fixer

before_script:
  - mkdir -p build/logs
  - wget https://github.com/infection/infection/releases/download/0.20.2/infection.phar
  - chmod +x infection.phar

install:
  - travis_retry composer install --no-interaction

script:
  - ./vendor/bin/phpunit --configuration ./phpunit.xml --coverage-clover=coverage.clover
  - ./infection.phar --min-msi=60 --min-covered-msi=60
  - ./vendor/bin/psalm --config=psalm.xml
  - ./vendor/bin/phpstan analyse src --level 7
  - ./vendor/bin/php-cs-fixer fix --allow-risky=yes --dry-run

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
